language: java
sudo: false
script: mvn clean verify

before_install:
  - git clone https://github.com/sosy-lab/cpachecker.git $CPAChecker
  - cd cpachecker
  - ant build
  - mkdir /tmp/cpacep/original
  - scripts/cpa.sh -spec config/specification/default.spc -config config/default.properties doc/examples/example.c -outputpath /tmp/cpacep/original -stats
  - git clone https://github.com/SupunArunoda/CPACEP.git $CPACEP
  
