language: java
sudo: false
script: mvn clean verify

before_install:
  - git clone https://github.com/sosy-lab/cpachecker.git $CPAChecker
  - cd $CPAChecker
  - sed -i -e 's/\r$//' scripts/cpa.sh
  - scripts/cpa.sh -spec config/specification/JavaAssertion.spc -config config/invariantGeneration.properties doc/examples/example.c
  - vim output/CPALog.txt
  
